### ISSUE TITLE
安装完kibana遇到的几个问题

### ISSUE THREAD

**Issue by HIShengBo** [Jarrettluo/all-documents-vue#4]
我在安装完kibana之后，不知道如何找到如何作者的windows安装操作，下面做下解答：
kibana可以搜索：
![52646ae46e9397319ef2af51b2118c0](https://user-images.githubusercontent.com/25527306/224237591-25b39b74-aeb5-4373-972f-aab4c3a52809.png)
出现下面问题解决方法
![45bb05351e3b55aee305db21cc41553](https://user-images.githubusercontent.com/25527306/224237416-c0487fda-2172-4c75-b473-35bfea95dafc.png)

配置文本抽取管道
Ingest Attachment Processor Plugin是一个文本抽取插件，本质上是利用了Elasticsearch的ingest node功能，提供了关键的预处理器attachment。在安装目录下运行以下命令即可安装。

`./bin/elasticsearch-plugin install ingest-attachment`

**Comment by Jarrettluo** [comment]
good!
