### ISSUE TITLE
按照Windows部署步骤启动前台报错

### ISSUE THREAD

**Issue by ruralqiu** [Jarrettluo/all-documents-vue#8]
出错: undefined，网络请求不存在是啥原因

**Comment by ruralqiu** [comment]
![Uploading 5ab237857b1625d48c50e905640b3ae.png…]()

**Comment by ruralqiu** [comment]
![5ab237857b1625d48c50e905640b3ae](https://user-images.githubusercontent.com/100115904/236792710-ec33cdbe-8dfa-4537-b16d-a49a1d752dcc.png)

**Comment by Jarrettluo** [comment]
修改request.js 下的url地址，修改为localhost
